/**
 * dsh-model-pricing — browser half.
 *
 * Registers the pricing section into the Models page footer slot and, later, the
 * per-provider card badges. Uses only cordis client context services (`slots`,
 * `locale`, `connection`) and its own components — no value imports from other DSH
 * client packages (bundle-purity rule). Falls back to an embedded snapshot when the
 * host route is unavailable (headless composition, offline browser).
 */
import * as React from 'react'
import { createStore } from './store.js'
import { PricingTable } from './PricingTable.js'
import { StatusLine } from './PricingTable.js'
import type { PricingPayload } from './types.js'
// Embedded offline fallback: build-time generated by scripts/build-snapshot.mjs.
import fallbackData from '../../data/snapshot.json'

export const name = 'dsh-model-pricing'
export const inject = ['slots']

const store = createStore((fallbackData as PricingPayload) ?? null)

const style: React.CSSProperties = {
  marginTop: 4,
  display: 'flex',
  flexDirection: 'column',
  gap: 2,
}

function PricingSection() {
  React.useEffect(() => {
    void store.load()
  }, [])
  const state = useStoreState()
  return (
    <section style={style} aria-labelledby="dsh-model-pricing-title">
      <div style={{ display: 'flex', alignItems: 'baseline', gap: 10, flexWrap: 'wrap' }}>
        <h3 id="dsh-model-pricing-title" style={{ fontSize: 15, fontWeight: 600, margin: 0 }}>Model pricing</h3>
        <span style={{ marginLeft: 'auto', display: 'flex', gap: 8, alignItems: 'center' }}>
          <StatusLine store={store} />
          <button
            style={{ font: 'inherit', color: 'inherit', background: 'transparent', border: '1px solid var(--dsw-alias-border-l2)', borderRadius: 6, padding: '3px 9px', cursor: 'pointer' }}
            aria-busy={state.status === 'loading'}
            onClick={() => void store.refresh()}
            title="Refresh catalog from the source"
          >↻ Refresh</button>
          <button
            style={{ font: 'inherit', color: 'inherit', background: 'transparent', border: 'none', cursor: 'pointer', padding: '3px 6px' }}
            aria-expanded={!state.collapsed}
            onClick={() => store.setCollapsed(!state.collapsed)}
          >{state.collapsed ? 'Show' : 'Hide'}</button>
        </span>
      </div>
      {!state.collapsed && <PricingTable store={store} />}
    </section>
  )
}

function useStoreState() {
  return useSyncExternalStoreCompat(store.subscribe, store.getState)
}

function useSyncExternalStoreCompat<S>(subscribe: (l: () => void) => () => void, get: () => S): S {
  // DSH ships React 18; useSyncExternalStore exists there. Kept as a local helper
  // to avoid importing react internals beyond the public surface.
  const useSES = (React as any).useSyncExternalStore as (<T>(sub: (l: () => void) => () => void, get: () => T) => T) | undefined
  if (useSES) return useSES(subscribe, get)
  const [snap, setSnap] = React.useState(get)
  React.useEffect(() => subscribe(() => setSnap(get())), [subscribe, get])
  return snap
}

export function apply(ctx: any) {
  ctx.slots.inject('settings.models.footer', () =>
    ctx.slots.register({ name: 'settings.models.footer', id: 'model-pricing', order: 100 }, PricingSection))
}
