/**
 * dsh-model-pricing — browser half.
 *
 * Registers the pricing section into the Models page footer slot. Uses only
 * cordis client context services (`slots`, `locale`) and its own components — no
 * value imports from other DSH client packages (bundle-purity rule). Falls back
 * to an embedded snapshot when the host serves the route but upstream is down;
 * renders nothing when the host half itself is not mounted (MVP DoD #5).
 *
 * Localization: registers en/zh dictionaries (DSH's built-in locales) plus a
 * Russian language pack — `addLanguage({ id: 'ru' })` makes Russian selectable
 * and re-evaluates the browser language list, so a Russian browser activates it
 * automatically. The harness UI itself ships only en/zh; this plugin adds ru.
 */
import * as React from 'react'
import { createStore } from './store.js'
import { PricingTable, PricingHeader, makeProviderBadge } from './PricingTable.js'
import { PricingSettingsCard } from './SettingsCard.js'
import { bindTranslator } from './i18n.js'
import { en, zh, ru } from './locales.js'
import type { PricingPayload } from './types.js'
// Embedded offline fallback: build-time generated by scripts/build-snapshot.mjs.
import fallbackData from '../../data/snapshot.json'

export const name = 'dsh-model-pricing'
export const inject = ['slots', 'locale']

const NS = 'model-pricing'
const store = createStore((fallbackData as PricingPayload) ?? null)

function wireLocale(ctx: any): void {
  const locale = ctx.locale
  if (!locale) return
  try {
    ctx.effect(() => locale.register(NS, 'en', en))
    ctx.effect(() => locale.register(NS, 'zh', zh))
    ctx.effect(() => locale.register(NS, 'ru', ru))
    const hasRu = (locale.getSnapshot?.().locales ?? []).some((l: { id: string }) => l.id === 'ru')
    if (!hasRu) ctx.effect(() => locale.addLanguage({ id: 'ru', label: 'Русский', fallback: 'en' }))
    const translate = locale.bind(NS)
    bindTranslator((key: string, params?: Record<string, string | number>) => translate(key, params))
    // Re-render mounted outlets when the active language changes.
    ctx.effect(() => locale.subscribe(() => store.notify()))
  } catch {
    // i18n shim already renders English; a locale-service anomaly must not hide the section.
  }
}

function PricingSection() {
  React.useEffect(() => {
    void store.load()
  }, [])
  const state = useStoreState()
  if (state.status === 'absent') return null // host half not mounted (standard slot absence)
  return (
    <section style={style} aria-labelledby="dsh-model-pricing-title">
      <PricingHeader store={store} />
      {!state.collapsed && <PricingTable store={store} />}
    </section>
  )
}

const style: React.CSSProperties = {
  marginTop: 4,
  display: 'flex',
  flexDirection: 'column',
  gap: 2,
}

function useStoreState() {
  return useSyncExternalStoreCompat(store.subscribe, store.getState)
}

function useSyncExternalStoreCompat<S>(subscribe: (l: () => void) => () => void, get: () => S): S {
  const useSES = (React as any).useSyncExternalStore as (<T>(sub: (l: () => void) => () => void, get: () => T) => T) | undefined
  if (useSES) return useSES(subscribe, get)
  const [snap, setSnap] = React.useState(get)
  React.useEffect(() => subscribe(() => setSnap(get())), [subscribe, get])
  return snap
}

export function apply(ctx: any) {
  wireLocale(ctx)
  ctx.slots.inject('settings.models.footer', () =>
    ctx.slots.register({ name: 'settings.models.footer', id: 'model-pricing', order: 100 }, PricingSection))
  // E4: an editable card on the Plugins settings tab, claimed by the namespace the
  // host registers. Optional seam: without settingsScope (a composition with no
  // settings UI) nothing renders and nothing throws.
  ctx.inject(['settingsScope'], (c: any) => {
    try {
      const scope = c.settingsScope.bind({ namespace: NS })
      c.slots.inject('settings.plugin.item', () =>
        c.slots.register({ name: 'settings.plugin.item', key: NS, id: 'model-pricing', order: 10 }, () => (
          React.createElement(PricingSettingsCard, { scope })
        )))
      // C1: provider-card badges on the Models page. LLM adapters own settings
      // namespaces named `llm-<provider>`; entries are registered for each served
      // namespace and the page dispatches only those that back a visible provider
      // row, passing the provider entry as props.
      const face = c.settingsScope.describe()
      const registered = new Set<string>()
      const badge = makeProviderBadge(store)
      const syncCards = () => {
        const view = face.getSnapshot().view
        if (!view) return
        for (const d of view.namespaces ?? []) {
          const ns = typeof d?.ns === 'string' ? d.ns : ''
          if (!ns.startsWith('llm-') || registered.has(ns)) continue
          registered.add(ns)
          c.slots.inject('settings.models.provider-card', () =>
            c.slots.register({ name: 'settings.models.provider-card', key: ns, id: `model-pricing/${ns}`, order: 50 }, badge))
        }
      }
      c.effect(face.subscribe(syncCards))
      void Promise.resolve(face.ensure?.()).then(syncCards).catch(() => {})
    } catch {
      // binding anomalies must never break the settings page itself
    }
  })
}
