/**
 * dsh-model-pricing — browser half.
 *
 * Registers the pricing section into the Models page footer slot, the
 * configuration card for this plugin's own settings section, and the per-provider
 * price badges on the Models page. Uses only cordis client context services
 * (`slots`, `locale`, `configForms`, `settingsScope`) and its own components — no
 * value imports from other DSH client packages (bundle-purity rule). Falls back
 * to an embedded snapshot when the host serves the route but upstream is down;
 * renders nothing when the host half itself is not mounted (MVP DoD #5).
 *
 * Two settings models are supported side by side, each armed only where its
 * service exists: 0.1.7+ exposes the row's `Config` through `configForms` and the
 * keyed `plugins.row.config` slot, while 0.1.5 keeps the imperative
 * `settingsScope` + `settings.plugin.item` pair. No version is ever sniffed.
 *
 * Localization: registers en/zh dictionaries (DSH's built-in locales) plus a
 * Russian language pack — `addLanguage({ id: 'ru' })` makes Russian selectable
 * and re-evaluates the browser language list, so a Russian browser activates it
 * automatically. The harness UI itself ships only en/zh; this plugin adds ru.
 */
import * as React from 'react'
import { createStore } from './store.js'
import { PricingTable, PricingHeader, makeProviderBadge } from './PricingTable.js'
import { PricingSettingsCard } from './SettingsCard.js'
import { bindTranslator } from './i18n.js'
import { en, zh, ru } from './locales.js'
import { ROW_CONFIG_KEY, ROW_NAMESPACE, SETTINGS_NAMESPACE } from '../shared/config.mjs'
import type { PricingPayload } from './types.js'
// Embedded offline fallback: build-time generated by scripts/build-snapshot.mjs.
import fallbackData from '../../data/snapshot.json'

export const name = 'dsh-model-pricing'
export const inject = ['slots', 'locale']

const NS = 'model-pricing'
const store = createStore((fallbackData as PricingPayload) ?? null)

function wireLocale(ctx: any): void {
  const locale = ctx.locale
  if (!locale) return
  try {
    ctx.effect(() => locale.register(NS, 'en', en))
    ctx.effect(() => locale.register(NS, 'zh', zh))
    ctx.effect(() => locale.register(NS, 'ru', ru))
    const hasRu = (locale.getSnapshot?.().locales ?? []).some((l: { id: string }) => l.id === 'ru')
    if (!hasRu) ctx.effect(() => locale.addLanguage({ id: 'ru', label: 'Русский', fallback: 'en' }))
    const translate = locale.bind(NS)
    bindTranslator((key: string, params?: Record<string, string | number>) => translate(key, params))
    // Re-render mounted outlets when the active language changes.
    ctx.effect(() => locale.subscribe(() => store.notify()))
  } catch {
    // i18n shim already renders English; a locale-service anomaly must not hide the section.
  }
}

function PricingSection() {
  React.useEffect(() => {
    void store.load()
  }, [])
  const state = useStoreState()
  if (state.status === 'absent') return null // host half not mounted (standard slot absence)
  return (
    <section style={style} aria-labelledby="dsh-model-pricing-title">
      <PricingHeader store={store} />
      {!state.collapsed && <PricingTable store={store} />}
    </section>
  )
}

const style: React.CSSProperties = {
  marginTop: 4,
  display: 'flex',
  flexDirection: 'column',
  gap: 2,
}

function useStoreState() {
  return useSyncExternalStoreCompat(store.subscribe, store.getState)
}

function useSyncExternalStoreCompat<S>(subscribe: (l: () => void) => () => void, get: () => S): S {
  const useSES = (React as any).useSyncExternalStore as (<T>(sub: (l: () => void) => () => void, get: () => T) => T) | undefined
  if (useSES) return useSES(subscribe, get)
  const [snap, setSnap] = React.useState(get)
  React.useEffect(() => subscribe(() => setSnap(get())), [subscribe, get])
  return snap
}

/**
 * C1: provider-card badges on the Models page. LLM adapters own settings
 * namespaces named `llm-<provider>`; an entry is registered for every served
 * namespace and the page dispatches only those that back a visible provider row.
 *
 * Both settings models expose the same describe face (`getSnapshot().view`,
 * `subscribe`, `ensure`), so this runs unchanged on either — it is called from
 * `configForms.describe()` on 0.1.7 and `settingsScope.describe()` on 0.1.5.
 *
 * @param c - the injected settings context, used to own the subscriptions.
 * @param face - the shared settings mirror returned by `describe()`.
 */
function registerProviderBadges(c: any, face: any): void {
  const registered = new Set<string>()
  const badge = makeProviderBadge(store)
  const syncCards = () => {
    const view = face.getSnapshot().view
    if (!view) return
    for (const d of view.namespaces ?? []) {
      const ns = typeof d?.ns === 'string' ? d.ns : ''
      if (!ns.startsWith('llm-') || registered.has(ns)) continue
      registered.add(ns)
      c.slots.inject('settings.models.provider-card', () =>
        c.slots.register({ name: 'settings.models.provider-card', key: ns, id: `model-pricing/${ns}`, order: 50 }, badge))
    }
  }
  c.effect(face.subscribe(syncCards))
  void Promise.resolve(face.ensure?.()).then(syncCards).catch(() => {})
}

/**
 * DSH 0.1.7+ — the plugin manager page asks for this row's configuration.
 *
 * The row's settings section is its own Loader row's `Config`, addressed by the
 * row id and keyed in the `plugins.row.config` slot by `<package>#<row id>`.
 * The page draws the title and crumb around the form, so the card drops its own
 * heading. `view: 'summary'` is the row's one-liner, used only when the package
 * carries no description of its own — this package has one, so the page never
 * asks, and returning nothing keeps a single source for that line.
 *
 * @param ctx - the browser plugin context.
 */
function registerRowConfig(ctx: any): void {
  ctx.inject(['configForms'], (c: any) => {
    try {
      const card = (props: { view?: string }) =>
        props?.view === 'summary'
          ? null
          : React.createElement(PricingSettingsCard, { scope: c.configForms.get(ROW_NAMESPACE), heading: false })

      const register = () =>
        c.slots.inject('plugins.row.config', () =>
          c.slots.register({ name: 'plugins.row.config', key: ROW_CONFIG_KEY, locale: NS }, card))

      // `whileServed` keeps the registration alive only while the Host actually
      // serves our namespace, so a deployment that never composed us shows no
      // trace of the entry.
      if (typeof c.configForms?.whileServed === 'function') {
        c.effect(() => c.configForms.whileServed([ROW_NAMESPACE], register), 'dsh-model-pricing: row configuration page')
      } else {
        register()
      }
      registerProviderBadges(c, c.configForms.describe())
    } catch {
      // A slot anomaly must never break the Plugins page itself.
    }
  })
}

/**
 * DSH 0.1.5 — the Plugins settings tab, keyed by the settings namespace the host
 * registered imperatively with `ctx.settings.installSection`.
 *
 * @param ctx - the browser plugin context.
 */
function registerSettingsItem(ctx: any): void {
  ctx.inject(['settingsScope'], (c: any) => {
    try {
      const scope = c.settingsScope.bind({ namespace: SETTINGS_NAMESPACE })
      c.slots.inject('settings.plugin.item', () =>
        c.slots.register({ name: 'settings.plugin.item', key: SETTINGS_NAMESPACE, id: 'model-pricing', order: 10 }, () =>
          React.createElement(PricingSettingsCard, { scope })))
      registerProviderBadges(c, c.settingsScope.describe())
    } catch {
      // Binding anomalies must never break the settings page itself.
    }
  })
}

export function apply(ctx: any) {
  wireLocale(ctx)
  ctx.slots.inject('settings.models.footer', () =>
    ctx.slots.register({ name: 'settings.models.footer', id: 'model-pricing', order: 100 }, PricingSection))
  // E4: an editable card for this plugin's own configuration. The two settings
  // models live behind different services — 0.1.7 has `configForms` and no
  // `settingsScope`, 0.1.5 the reverse — so each path arms only where it exists
  // and no version is ever sniffed.
  registerRowConfig(ctx)
  registerSettingsItem(ctx)
}
